EvgeniyArabadzhiyskiy/Filmoteka-project

src/library.html
src/partials/home/header.html
src/sass/components/_library.scss
src/sass/index.scss

add section library, add sass library, create link to library from index.html and reverse link to index from library

section library

---

src/library.html
src/sass/components/_library.scss

Fix width on 320,768,1024px
Add  footer part

library fixed

---

src/library.html

library section

---

src/index.html
src/index.js
src/js/apiService.js
src/js/pagination.js
src/partials/home/pagination.html
src/sass/components/_footer.scss
src/sass/components/_pagination.scss
src/sass/index.scss
src/sass/utils/_base.scss

1. Додала js, scss. html файли для пагінації
2. Підключила їх в index.html/js/scss
3. В файлі з фетчами додали у фетч параметр page, бо так треба для пагінації
4. Поправила стилі в загальному контейнері (бекграунд колір) і додала падінги у футері, як на макеті

Додає пагінацію

---

src/js/pagination.js

Зміни в файлі pagination.js.
Був баг: (1 ... 2 3 4 5 6 ... 1000),
(1 ... 995 996 997 998 999 ... 1000),
тепер: (1 ... 3 4 5 6 7 ... 1000),
(1 ... 994 995 996 997 998 ... 1000),

Fix pagination dots

---

src/js/modal-open.js
src/partials/home/modal.html

close modal

---

src/index.js
src/js/apiService.js
src/js/movieSearch.js
src/js/pagination.js

add condition in paggination.js for search and create separate js file "movieSearch.js"

fix search bug

---

package-lock.json
package.json
src/index.js
src/js/helpers/back-to-top.js

для установки плагина 
$ npm install --save vanilla-back-to-top
Создала папку helpers для всяких вспомогательных плагинов типа свайперов и скролов. думаю при рефакторинге она понадобится.

add back-to-top scroll

---

src/index.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#154

Revert "update index"

---

src/index.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#152

Revert "fix/update index.js"

---

src/js/library.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#151

Revert "fix path cursor"

---

src/js/library.js
src/js/modal-open.js
src/js/paginationLibrary.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#147

Revert "adaptive render card library and scroll"

---

src/sass/components/_header.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#146

Revert "fix margin"

---

package-lock.json
src/js/movieSearch.js
src/partials/home/header.html
src/sass/components/_modal.scss
src/sass/components/_pagination.scss
src/sass/utils/_base.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#145

Revert "Styles change"

---

src/sass/components/_modal.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#144

Revert "modal"

---

src/index.js
src/js/pagination.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#141

Revert "fix/path"

---

src/index.js
src/js/pagination.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#168

Revert "Revert "fix/path""

---

src/sass/components/_header.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#167

Revert "Revert "fix header margin""

---

src/index.js
src/js/modal-open.js
src/js/templates/modalMarkup.js
src/js/templates/renderMovieModal.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#166

Revert "Revert "refactoring modal""

---

src/sass/components/_modal.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#163

Revert "Revert "modal""

---

src/sass/components/_header.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#161

Revert "Revert "fix margin""

---

src/partials/home/header.html
src/sass/components/_dark-thema.scss
src/sass/components/_header.scss
src/sass/index.scss
src/sass/utils/_base.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#159

Revert "Revert "fix header and thema""

---

src/js/library.js

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#157

Revert "Revert "fix path cursor""

---

src/js/auth.js
src/js/helpers/auth-btn-action.js
src/js/helpers/firebase-config.js
src/js/helpers/initialize-firebase.js
src/js/library.js
src/partials/home/header.html

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#182

Revert "Revert "Feature auth""

---

src/partials/home/header.html
src/sass/components/_dark-thema.scss
src/sass/components/_header.scss
src/sass/index.scss
src/sass/utils/_base.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#188

Revert "Revert "Revert "Revert "fix header and thema""""

---

src/js/components/team-modal.js
src/sass/components/_modal-team.scss

Reverts EvgeniyArabadzhiyskiy/Filmoteka-project#215

Revert "fix background and close on escape"
